version: "3.9"
   
services:
  db:
    image: mysql
    container_name: hospital_db
    volumes:
      - ../../db/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "hospital_db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      # MYSQL_USER: "djangouser"
      # MYSQL_PASSWORD: "ismail123"
  app:
    container_name: hospital_app
    build: app/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  web:
    restart: always
    build: web/
    container_name: hospital_web
    image: nginx
    volumes:
      - ../../staticfiles:/srv/staticfiles
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - "app"