# Generated by Django 3.2.6 on 2021-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20210811_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cf',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
