# Generated by Django 3.2.6 on 2021-08-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_appointment_cf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cf',
        ),
    ]
