# Generated by Django 3.2.6 on 2021-08-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_patientuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientUser',
        ),
    ]
