# Generated by Django 3.2.6 on 2021-08-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identifier',
            field=models.CharField(default='ismail', max_length=40, unique=True),
        ),
    ]
