# Generated by Django 3.2.6 on 2021-08-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_patient_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identifier',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
