# Generated by Django 3.2.6 on 2021-08-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_auto_20210820_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='record',
            name='doctor',
        ),
    ]
