# Generated by Django 3.2.6 on 2021-08-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0013_auto_20210823_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='identifier',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='PatientName', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='PatientLastName', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
