# Generated by Django 3.2.6 on 2021-08-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_auto_20210823_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
