# Generated by Django 3.2.6 on 2021-08-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_auto_20210823_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='record',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='result',
            name='patient',
        ),
    ]
