# Generated by Django 3.2.6 on 2021-08-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_auto_20210823_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
