# Generated by Django 3.2.6 on 2021-08-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='approved',
        ),
    ]
