# Generated by Django 3.2.6 on 2021-08-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='newapp.patient'),
        ),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='newapp.patient'),
        ),
        migrations.AddField(
            model_name='result',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='newapp.patient'),
        ),
    ]
