# Generated by Django 3.2.6 on 2021-08-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0024_auto_20210823_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.patient'),
        ),
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.patient'),
        ),
        migrations.AlterField(
            model_name='result',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.patient'),
        ),
    ]
