# Generated by Django 3.2.6 on 2021-09-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0030_alter_result_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
