# Generated by Django 3.2.6 on 2021-09-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0031_auto_20210902_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session',
            field=models.TimeField(choices=[(1, '10.00-10.30'), (2, '10.30-11.00'), (3, '11.00-11.30'), (4, '11.30-12.00'), (5, '14.00-14.30'), (6, '14.30-15.00'), (7, '15.00-15.30'), (8, '15.30-16.00'), (9, '16.00-16.30'), (10, '16.30-17.00')], null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
