# Generated by Django 3.2.6 on 2021-09-03 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0032_auto_20210903_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session',
            field=models.TimeField(choices=[(1, datetime.time(10, 0)), (2, datetime.time(10, 30)), (3, datetime.time(11, 0)), (4, datetime.time(11, 30)), (5, datetime.time(14, 0)), (6, datetime.time(14, 30)), (7, datetime.time(15, 0)), (8, datetime.time(15, 30)), (9, datetime.time(16, 0)), (10, datetime.time(16, 30))], null=True),
        ),
    ]
