# Generated by Django 3.2.6 on 2021-09-03 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0033_alter_appointment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session',
            field=models.TimeField(choices=[(datetime.time(10, 0), '10.00-10.30'), (datetime.time(10, 30), '10.30-11.00'), (datetime.time(11, 0), '11.00-11.30'), (datetime.time(11, 30), '11.30-12.00'), (datetime.time(14, 0), '14.00-14.30'), (datetime.time(14, 30), '14.30-15.00'), (datetime.time(15, 0), '15.00-15.30'), (datetime.time(15, 30), '15.30-16.00'), (datetime.time(16, 0), '16.00-16.30'), (datetime.time(16, 30), '16.30-17.00')], null=True),
        ),
    ]
