# Generated by Django 3.2.7 on 2021-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0038_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
